### ISSUE TITLE
optimize entity ai

### ISSUE THREAD

**Issue by MimzyFang** [Sollace/Unicopia#92]

**Comment by Sollace** [comment]
I assume by closing this, it means the lag is resolved?

**Comment by MimzyFang** [comment]
It's still not perfect but it's better on my test situations I still need to check how well it would work on the server since I still haven't deployed the new version because I'm waiting for the modrinth release
